# Generated by Django 3.1.4 on 2020-12-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201230_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_address',
            new_name='address',
        ),
    ]
