# Generated by Django 3.1.4 on 2021-01-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='proudct',
            new_name='product',
        ),
    ]
