# Generated by Django 3.1.4 on 2021-01-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210103_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.FileField(max_length=2000, null=True, upload_to=''),
        ),
    ]
