# Generated by Django 3.1.4 on 2021-01-04 18:25

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210103_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.user_directory_path),
        ),
    ]
