# Generated by Django 3.1.4 on 2020-12-30 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nearby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('viewed', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'nearbys',
            },
        ),
        migrations.CreateModel(
            name='NearbyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'nearbycategories',
            },
        ),
        migrations.CreateModel(
            name='NearbyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('nearby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nearby.nearby')),
            ],
            options={
                'db_table': 'nearbyimages',
            },
        ),
        migrations.CreateModel(
            name='NearbyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('nearby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nearby.nearby')),
            ],
            options={
                'db_table': 'nearbycomments',
            },
        ),
    ]
