# Generated by Django 3.1.4 on 2020-12-30 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nearby', '0001_initial'),
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbycomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AddField(
            model_name='nearbycategory',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.maincategory'),
        ),
        migrations.AddField(
            model_name='nearby',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_nearby', to='user.address'),
        ),
        migrations.AddField(
            model_name='nearby',
            name='comment_id',
            field=models.ManyToManyField(through='nearby.NearbyComment', to='user.User'),
        ),
        migrations.AddField(
            model_name='nearby',
            name='nearby_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nearby.nearbycategory'),
        ),
        migrations.AddField(
            model_name='nearby',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploader_nearby', to='user.user'),
        ),
    ]
