# Generated by Django 3.1.4 on 2021-01-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201230_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulladdress',
            name='usage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
