# Generated by Django 3.1.4 on 2021-01-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210104_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='dong',
            new_name='region',
        ),
    ]
