# Generated by Django 3.1.4 on 2021-01-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210104_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='sigungu',
            new_name='neighborhood',
        ),
    ]
