# Generated by Django 3.1.4 on 2021-01-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210104_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='sido',
            new_name='district',
        ),
    ]
